tunnel: 279494ef-35da-48d3-971b-93c40cc6b70e
credentials-file: /home/zhukunren/.cloudflared/279494ef-35da-48d3-971b-93c40cc6b70e.json
ingress:
  - hostname: kline.dwzq.top
    service: http://localhost:5173
  - service: http_status:404
